baseURL: https://blog.ransewhale.net/
languageCode: ja-JP
title: "ransewhale's blog"
theme: mini

# Default content language, support en (English) / zh (Chinese) / nl (Dutch), default 'en'
defaultContentLanguage: ja

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
# themesDir: ../../

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: rw-blog

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  twitter: 323O65281
  github: ransewhale
  # stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: ransewhale
  # Author biography
  bio: こういうところに文章を書けと言われると困る
  # Site Description, used in HTML meat
  description: ransewhale's blog


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: false
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: true
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '' 

  # Extra links in navigation
  links:
    - name: Website
      path: https://ransewhale.net/
      target: _BLANK
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js